Add "file-output-argument" parameter to the `snyk test` command.
Issue trying to solve: Adding the option
"--json-file-oupt=..." to "additional-arguments" parameter will cause the snyk
monitor to fail.

Error: "The following option combination is not currently supported:
monitor + json-file-output"